import type { Game } from "../../../config/types.ts";

// 从 GitHub 导入的 HTML5 游戏(经筛 MIT)。Generated by scripts/import-games.mjs. 保留原作者署名。
const IMPORTED: Game[] = [

];

export function getImportedGames(): Game[] { return IMPORTED; }
