// import-games.mjs — 从 GitHub 公开仓库下载自包含单文件 HTML5 游戏并接入 darlynmae。
// 沙箱无法连 GitHub, 请在用户本机运行 (Node 22+):
//   无参数: 导入内置 CURATED 清单(已筛 MIT / 单文件 / 零依赖)
//   指定:   node scripts/import-games.mjs <owner/repo> [subdir] [branch]
//
// 重要(商用合规):
//   - 仅导入明确 MIT 或允许商用的仓库, 并在游戏页保留原作者署名。
//   - 导入的游戏是第三方完整 HTML(自带开始/重开/音效), 直接以 iframe 嵌入, 不经我们 buildHTML 外壳。
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const D = dirname(fileURLToPath(import.meta.url));
const ROOT = join(D, "..");

// 内置精选: 仅收录明确 MIT / 零依赖 / 单文件的仓库。商用合规优先。
const CURATED = [
  { repo: "chaoxucoding/spacebattle", subdir: "", branch: "main", note: "MIT; 单文件太空射击" },
  { repo: "wuhao199368/idle-html", subdir: "", branch: "main", note: "MIT; 多款单文件 idle 点击器" },
  { repo: "drakeaxelrod/single-html-file-apps", subdir: "", branch: "main", note: "MIT; 含 snake/slots(零依赖), pong 用 Phaser 会被自动跳过" },
];

// 命中即跳过: 该 HTML 引用了外部依赖, iframe 加载会缺资源。
const EXTERNAL = [
  /cdn\./i, /unpkg\.com/i, /jsdelivr/i, /googleapis\.com/i, /google\.com\/fonts/i,
  /<script[^>]+src=["']https?:/i, /phaser|three\.?js|cdn\.jsdelivr/i,
];

const arg = process.argv[2];
const targets = arg && arg.includes("/")
  ? [{ repo: arg, subdir: process.argv[3] || "", branch: process.argv[4] || "main" }]
  : CURATED;

let imported = 0, skipped = 0;
const entries = [];

// 递归收集任意深度的单文件 .html(含外部依赖的会被后续 EXTERNAL 过滤跳过)。
async function collectHtml(repo, branch, path, acc) {
  const res = await fetch(`https://api.github.com/repos/${repo}/contents/${path}?ref=${branch}`, {
    headers: { Accept: "application/vnd.github+json", "User-Agent": "darlynmae-importer" },
  });
  if (!res.ok) return;
  const items = await res.json();
  for (const it of items) {
    if (it.type === "dir") await collectHtml(repo, branch, it.path, acc);
    else if (it.name.endsWith(".html") && it.type === "file") acc.push(it);
  }
}

for (const t of targets) {
  const { repo, subdir, branch } = t;
  console.log(`\n== ${repo} (${t.note || ""}) ==`);
  const files = [];
  await collectHtml(repo, branch, subdir, files);
  if (!files.length) { console.warn("  未发现任何 .html, 跳过"); skipped++; continue; }

  for (const f of files) {
    const slug = f.name.replace(/\.html$/i, "").toLowerCase().replace(/[^a-z0-9-]+/g, "-");
    const raw = await fetch(`https://raw.githubusercontent.com/${repo}/${branch}/${f.path}`);
    if (!raw.ok) { console.warn("  跳过", f.path, raw.status); skipped++; continue; }
    const html = await raw.text();
    if (EXTERNAL.some((re) => re.test(html))) { console.log("  跳过(含外部依赖)", f.path); skipped++; continue; }
    const dir = join(ROOT, "public/games", slug);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "index.html"), html);
    console.log("  导入", slug, `(${repo})`);
    imported++;
    entries.push({ slug, title: f.name.replace(/\.html$/i, ""), repo });
  }
}

const out = `import type { Game } from "../../../config/types.ts";\n\n// 从 GitHub 导入的自包含 HTML5 游戏(经筛 MIT/零依赖)。Generated by scripts/import-games.mjs.\nconst IMPORTED: Game[] = [\n${
  entries.map((e) =>
    `  { id:"imp-${e.slug}", slug:${JSON.stringify(e.slug)}, title:${JSON.stringify(e.title)}, category:"imported", description:"Imported HTML5 game from ${e.repo}.", emoji:"🎮", url:"/games/${e.slug}/", rating:4.5, plays:"0", siteIds:["default"], embedUrl:"/games/${e.slug}/index.html", instructions:"Play with mouse or keyboard.", content:{intro:"",gameplay:"",controls:"",features:"",faq:""}, width:480, height:480, tags:[], source:"imported", featured:false, popular:false, isNew:true },`
  ).join("\n")
}\n];\n\nexport function getImportedGames(): Game[] { return IMPORTED; }\n`;
writeFileSync(join(ROOT, "src/data/sources/selfhosted/games-imported.ts"), out);
console.log(`\n导入 ${imported} 款, 跳过 ${skipped} 款。已写 games-imported.ts。`);
console.log("下一步: 在 src/data/games.ts 合并 getImportedGames(); 然后 tsc + 本机 deploy.ps1 推送上线。");
