// import-games.mjs — 从 GitHub 公开仓库下载自包含单文件 HTML5 游戏并接入站点。
// 沙箱无法连 GitHub, 请在用户本机运行(Node 22+):
//   node scripts/import-games.mjs <owner/repo> [subdir] [branch]
// 例: node scripts/import-games.mjs "leungwensen/sliding-puzzle" "" main
//
// 注意: 仅导入"自包含单文件"HTML(游戏逻辑 inline, 不依赖外部 .js/.css)。
// 若 HTML 引用外部资源, iframe 加载后这些资源会 404。导入前请确认目标仓库的授权(MIT/CC0 等)。
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const D = dirname(fileURLToPath(import.meta.url));
const ROOT = join(D, "..");
const [repo, subdir = "", branch = "main"] = process.argv.slice(2);
if (!repo || !repo.includes("/")) {
  console.error("用法: node scripts/import-games.mjs <owner/repo> [subdir] [branch]");
  process.exit(1);
}
const api = `https://api.github.com/repos/${repo}/contents/${subdir}?ref=${branch}`;
const rawBase = `https://raw.githubusercontent.com/${repo}/${branch}`;

const res = await fetch(api, { headers: { Accept: "application/vnd.github+json", "User-Agent": "darlynmae-importer" } });
if (!res.ok) { console.error("列目录失败", res.status, await res.text()); process.exit(1); }
const items = await res.json();
const htmls = items.filter((i) => i.name.endsWith(".html") && i.type === "file");
console.log(`发现 ${htmls.length} 个 .html 文件`);

const entries = [];
for (const f of htmls) {
  const slug = f.name.replace(/\.html$/i, "").toLowerCase().replace(/[^a-z0-9-]+/g, "-");
  const raw = await fetch(rawBase + "/" + f.path);
  if (!raw.ok) { console.warn("跳过", f.path, raw.status); continue; }
  const html = await raw.text();
  const dir = join(ROOT, "public/games", slug);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "index.html"), html);
  console.log("导入", slug);
  entries.push({ slug, title: f.name.replace(/\.html$/i, "") });
}

const out = `import type { Game } from "../../../config/types.ts";\n\n// 从 GitHub 导入的自包含 HTML5 游戏。Generated by scripts/import-games.mjs.\nconst IMPORTED: Game[] = [\n${
  entries.map((e) =>
    `  { id:"imp-${e.slug}", slug:${JSON.stringify(e.slug)}, title:${JSON.stringify(e.title)}, category:"imported", description:"", emoji:"🎮", url:"/games/${e.slug}/", rating:4.5, plays:"0", siteIds:["default"], embedUrl:"/games/${e.slug}/index.html", instructions:"Play with mouse or keyboard.", content:{intro:"",gameplay:"",controls:"",features:"",faq:""}, width:480, height:480, tags:[], source:"imported", featured:false, popular:false, isNew:true },`
  ).join("\n")
}\n];\n\nexport function getImportedGames(): Game[] { return IMPORTED; }\n`;
writeFileSync(join(ROOT, "src/data/sources/selfhosted/games-imported.ts"), out);
console.log(`已写入 games-imported.ts (${entries.length} 款)。`);
console.log("下一步: 在 src/data/games.ts 中 import 并合并 getImportedGames(), 然后 tsc + 本机 deploy.ps1。");
